### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by SarvarKh** [Andrik27001/Anime-Revolution-2021-Capstone#2]
Please leave your comments below, if you have any

**Comment by SarvarKh** [comment]
**Well personalized and designed** :thumbsup:
Animations in the programs and partner sections of the main page look great  :star:

**Comment by akshay-narkar** [comment]
**Looks amazing! Very Well designed**

Can work on the guest part if needed

**Comment by Byabasaija** [comment]
You could use an hr instead of <p>______<p>. Otherwise, Your project is wow!

**Comment by wandji20** [comment]
Great work
